apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: app-sa-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: approle
subjects:
- kind: ServiceAccount
  name: app-sa
  namespace: app
