apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: app-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: approle
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: dev
