apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: approle
  namespace: app
rules:
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - create
  - update
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - pods
    services
  verbs:
  - create
  - list
  - update
  - delete
