apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: appRole
  namespace: app
  labels:
    app: nginx-deployment
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
  - list
  - create
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - create
  - update
