apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: testpod
  name: testpod
spec:
  containers:
  - image: alpine
    name: testpod
    command: [ "/bin/sh", "-c" ]
    args:
    - while true; do
        sleep 300;
      done;
  dnsPolicy: ClusterFirst
  restartPolicy: Always
