apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pv-testpod
  name: pv-testpod
spec:
  containers:
  - image: alpine
    name: pv-testpod
    command: [ "/bin/sh", "-c" ]
    args:
    - while true; do
        sleep 300;
      done;
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim
  dnsPolicy: ClusterFirst
  restartPolicy: Always
